version: "3.7"

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    image: myjenkins-blueocean:2.414.1-1
    build:
      context: .
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins-blueocean
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
