version: "3.7"

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - ./.jenkins/jenkins-docker-certs:/certs/client
      - ./.jenkins/jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    image: myjenkins-blueocean:2.438
    build:
      context: .
    ports:
      - 8083:8080
      - 50003:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./.jenkins/jenkins-data:/var/jenkins_home
      - ./.jenkins/jenkins-docker-certs:/certs/client:ro
      - ./:/var/jenkins_home/home
